# Generated by Django 4.1.6 on 2023-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_createprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
