# Generated by Django 4.1.6 on 2023-02-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_createprofile_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprofile',
            name='is_paid',
        ),
    ]
