# Generated by Django 4.1.6 on 2023-03-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songhistory', to='musicapp.song'),
        ),
    ]
