# Generated by Django 4.1.6 on 2023-03-24 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0007_song_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='fav',
            field=models.ManyToManyField(blank=True, null=True, related_name='userfavsong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
