# Generated by Django 4.1.6 on 2023-03-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='v_id',
        ),
        migrations.AddField(
            model_name='history',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie'),
        ),
    ]
