# Generated by Django 4.1.6 on 2023-03-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviehistory', to='movieapp.movie'),
        ),
    ]
