# Generated by Django 4.1.6 on 2023-03-21 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0007_alter_history_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fav',
            field=models.ManyToManyField(null=True, related_name='userfavmovie', to=settings.AUTH_USER_MODEL),
        ),
    ]
