# Generated by Django 4.1.6 on 2023-03-22 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_movie_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='movie',
            name='liked_by',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
