# Generated by Django 4.1.6 on 2023-03-22 19:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0009_remove_movie_liked_by_movie_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='movie',
            name='total_likes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
