# Generated by Django 4.1.6 on 2023-03-24 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0010_remove_movie_liked_by_alter_movie_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
