# Generated by Django 4.1.6 on 2023-03-24 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0011_alter_movie_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fav',
            field=models.ManyToManyField(blank=True, null=True, related_name='userfavmovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
