# Generated by Django 4.1.6 on 2023-03-19 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentriesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentriesapp.documentary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdocumentaryhistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
