# Generated by Django 4.1.6 on 2023-03-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentriesapp', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='documentary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentaryhistory', to='documentriesapp.documentary'),
        ),
    ]
