# Generated by Django 4.1.6 on 2023-03-22 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentriesapp', '0003_alter_history_documentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentary',
            name='total_likes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
