# Generated by Django 4.1.6 on 2023-03-22 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentriesapp', '0004_alter_documentary_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentary',
            name='fav',
            field=models.ManyToManyField(null=True, related_name='userfavdocumentray', to=settings.AUTH_USER_MODEL),
        ),
    ]
