# Generated by Django 4.1.6 on 2023-03-18 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='Location',
            field=models.CharField(default='not available', max_length=100),
        ),
        migrations.AddField(
            model_name='museum',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='museum',
            name='subscription_only',
            field=models.BooleanField(default=False),
        ),
    ]
