# Generated by Django 4.1.6 on 2023-02-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_subscription_plan_remove_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
